name: Discord Status Embed

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  send_embed:
    runs-on: ubuntu-latest
    name: Send an embed to Discord

    steps:
    - name: Run the GitHub Actions Status Embed Action
      uses: SebastiaanZ/github-status-embed-for-discord@main
      with:
        # Discord webhook
        webhook_id: '969774054133358653'
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}

        # We need to provide the information of the workflow that
        # triggered this workflow instead of this workflow.
        workflow_name: ${{ github.event.workflow_run.name }}
        run_id: ${{ github.event.workflow_run.id }}
        run_number: ${{ github.event.workflow_run.run_number }}
        status: ${{ github.event.workflow_run.conclusion }}
        sha: ${{ github.event.workflow_run.head_sha }}

        # Optional arguments for PR-related events
        # Note: There's no harm in including these lines for non-PR
        # events, as non-existing paths in objects will evaluate to
        # `null` silently and the github status embed action will
        # treat them as absent.
        pr_author_login: ${{ github.event.pull_request.user.login }}
        pr_number: ${{ github.event.pull_request.number }}
        pr_title: ${{ github.event.pull_request.title }}
        pr_source: ${{ github.event.pull_request.head.label }}